{%- if ci_platform == "github" -%}
name: Security audit

on:
  push:
    paths:
      - ".github/workflows/audit.yml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
{% if publish_audit_issues %}  checks: write
{% endif %}  contents: read
{% if publish_audit_issues %}  issues: write
{% endif %}
jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: {{ pin_github_action("actions/checkout", "v6") }}
        with:
          persist-credentials: false
{% if publish_audit_issues %}      - uses: {{ pin_github_action("rustsec/audit-check", "v2") }}
        with:
          token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
{% else %}      - uses: {{ pin_github_action("taiki-e/install-action", "v2") }}
        with:
          tool: cargo-audit
      - run: cargo audit --deny warnings --file ./Cargo.lock
{% endif %}
{%- endif %}
