{% raw %}[package]
name = "{{ project_name }}"
version = "0.1.0"
edition = "2024"
description = "{{ project_description }}"
{% endraw %}license = "MIT OR Apache-2.0"

[dependencies]
# you can declare dependencies normally, or reference
# versions managed by your battery pack:
# clap.bp-managed = true

