name: Typos
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  merge_group: ~
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.43.4
